// This file is generated by scripts/generate-modules.ts — do not edit by hand.
import { CompanyModule } from './administration/company/company.module';
import { StoreModule } from './administration/store/store.module';
import { RoleModule } from './administration/role/role.module';
import { PermissionModule } from './administration/permission/permission.module';
import { UserModule } from './administration/user/user.module';
import { ActivityLogModule } from './administration/activity-log/activity-log.module';
import { LanguageModule } from './administration/language/language.module';
import { CurrencyModule } from './administration/currency/currency.module';
import { SettingModule } from './settings/setting/setting.module';
import { CategoryModule } from './commerce/category/category.module';
import { BrandModule } from './commerce/brand/brand.module';
import { AttributeModule } from './commerce/attribute/attribute.module';
import { AttributeValueModule } from './commerce/attribute-value/attribute-value.module';
import { CollectionModule } from './commerce/collection/collection.module';
import { ProductModule } from './commerce/product/product.module';
import { ProductImageModule } from './commerce/product-image/product-image.module';
import { ProductVariantModule } from './commerce/product-variant/product-variant.module';
import { AuctionDetailModule } from './commerce/auction-detail/auction-detail.module';
import { BidModule } from './commerce/bid/bid.module';
import { PreorderDetailModule } from './commerce/preorder-detail/preorder-detail.module';
import { ReviewModule } from './commerce/review/review.module';
import { ProductQuestionModule } from './commerce/product-question/product-question.module';
import { WarehouseModule } from './inventory/warehouse/warehouse.module';
import { StockItemModule } from './inventory/stock-item/stock-item.module';
import { StockTransferModule } from './inventory/stock-transfer/stock-transfer.module';
import { StockAdjustmentModule } from './inventory/stock-adjustment/stock-adjustment.module';
import { StockCountModule } from './inventory/stock-count/stock-count.module';
import { ProductBatchModule } from './inventory/product-batch/product-batch.module';
import { SellerModule } from './marketplace/seller/seller.module';
import { CommissionModule } from './marketplace/commission/commission.module';
import { PayoutModule } from './marketplace/payout/payout.module';
import { CustomerGroupModule } from './customers/customer-group/customer-group.module';
import { CustomerModule } from './customers/customer/customer.module';
import { CustomerAddressModule } from './customers/customer-address/customer-address.module';
import { LoyaltyTransactionModule } from './customers/loyalty-transaction/loyalty-transaction.module';
import { OrderModule } from './sales/order/order.module';
import { OrderItemModule } from './sales/order-item/order-item.module';
import { PaymentModule } from './sales/payment/payment.module';
import { TransactionModule } from './sales/transaction/transaction.module';
import { InvoiceModule } from './sales/invoice/invoice.module';
import { ReturnModule } from './sales/return/return.module';
import { RefundModule } from './sales/refund/refund.module';
import { AbandonedCartModule } from './sales/abandoned-cart/abandoned-cart.module';
import { ShippingZoneModule } from './shipping/shipping-zone/shipping-zone.module';
import { ShippingRateModule } from './shipping/shipping-rate/shipping-rate.module';
import { CarrierModule } from './shipping/carrier/carrier.module';
import { PickupLocationModule } from './shipping/pickup-location/pickup-location.module';
import { DeliveryAgentModule } from './shipping/delivery-agent/delivery-agent.module';
import { ShipmentModule } from './shipping/shipment/shipment.module';
import { CouponModule } from './marketing/coupon/coupon.module';
import { PromotionModule } from './marketing/promotion/promotion.module';
import { FlashDealModule } from './marketing/flash-deal/flash-deal.module';
import { EmailCampaignModule } from './marketing/email-campaign/email-campaign.module';
import { SmsCampaignModule } from './marketing/sms-campaign/sms-campaign.module';
import { PushCampaignModule } from './marketing/push-campaign/push-campaign.module';
import { CampaignModule } from './marketing/campaign/campaign.module';
import { AffiliateModule } from './marketing/affiliate/affiliate.module';
import { AffiliateReferralModule } from './marketing/affiliate-referral/affiliate-referral.module';
import { SupplierModule } from './purchasing/supplier/supplier.module';
import { PurchaseRequestModule } from './purchasing/purchase-request/purchase-request.module';
import { RequestForQuotationModule } from './purchasing/request-for-quotation/request-for-quotation.module';
import { PurchaseOrderModule } from './purchasing/purchase-order/purchase-order.module';
import { PurchaseOrderItemModule } from './purchasing/purchase-order-item/purchase-order-item.module';
import { GoodsReceiptModule } from './purchasing/goods-receipt/goods-receipt.module';
import { PurchaseReturnModule } from './purchasing/purchase-return/purchase-return.module';
import { TaxClassModule } from './finance/tax-class/tax-class.module';
import { TaxRateModule } from './finance/tax-rate/tax-rate.module';
import { ExpenseModule } from './finance/expense/expense.module';
import { SellerSettlementModule } from './finance/seller-settlement/seller-settlement.module';
import { AccountingEntryModule } from './finance/accounting-entry/accounting-entry.module';
import { PageModule } from './content/page/page.module';
import { BlogCategoryModule } from './content/blog-category/blog-category.module';
import { BlogPostModule } from './content/blog-post/blog-post.module';
import { MenuModule } from './content/menu/menu.module';
import { BannerModule } from './content/banner/banner.module';
import { PopupModule } from './content/popup/popup.module';
import { MediaFileModule } from './content/media-file/media-file.module';
import { SupportTicketModule } from './support/support-ticket/support-ticket.module';
import { TicketReplyModule } from './support/ticket-reply/ticket-reply.module';
import { ContactMessageModule } from './support/contact-message/contact-message.module';
import { ComplaintModule } from './support/complaint/complaint.module';
import { KnowledgeBaseArticleModule } from './support/knowledge-base-article/knowledge-base-article.module';
import { NotificationModule } from './notifications/notification/notification.module';
import { NotificationTemplateModule } from './notifications/notification-template/notification-template.module';
import { ApiKeyModule } from './integrations/api-key/api-key.module';
import { WebhookModule } from './integrations/webhook/webhook.module';
import { WebhookLogModule } from './integrations/webhook-log/webhook-log.module';
import { IntegrationConnectionModule } from './integrations/integration-connection/integration-connection.module';
import { OtpRequestModule } from './integrations/otp-request/otp-request.module';
import { AiGenerationLogModule } from './ai-studio/ai-generation-log/ai-generation-log.module';
import { SavedReportModule } from './analytics/saved-report/saved-report.module';

export const ResourceModules = [
  CompanyModule,
  StoreModule,
  RoleModule,
  PermissionModule,
  UserModule,
  ActivityLogModule,
  LanguageModule,
  CurrencyModule,
  SettingModule,
  CategoryModule,
  BrandModule,
  AttributeModule,
  AttributeValueModule,
  CollectionModule,
  ProductModule,
  ProductImageModule,
  ProductVariantModule,
  AuctionDetailModule,
  BidModule,
  PreorderDetailModule,
  ReviewModule,
  ProductQuestionModule,
  WarehouseModule,
  StockItemModule,
  StockTransferModule,
  StockAdjustmentModule,
  StockCountModule,
  ProductBatchModule,
  SellerModule,
  CommissionModule,
  PayoutModule,
  CustomerGroupModule,
  CustomerModule,
  CustomerAddressModule,
  LoyaltyTransactionModule,
  OrderModule,
  OrderItemModule,
  PaymentModule,
  TransactionModule,
  InvoiceModule,
  ReturnModule,
  RefundModule,
  AbandonedCartModule,
  ShippingZoneModule,
  ShippingRateModule,
  CarrierModule,
  PickupLocationModule,
  DeliveryAgentModule,
  ShipmentModule,
  CouponModule,
  PromotionModule,
  FlashDealModule,
  EmailCampaignModule,
  SmsCampaignModule,
  PushCampaignModule,
  CampaignModule,
  AffiliateModule,
  AffiliateReferralModule,
  SupplierModule,
  PurchaseRequestModule,
  RequestForQuotationModule,
  PurchaseOrderModule,
  PurchaseOrderItemModule,
  GoodsReceiptModule,
  PurchaseReturnModule,
  TaxClassModule,
  TaxRateModule,
  ExpenseModule,
  SellerSettlementModule,
  AccountingEntryModule,
  PageModule,
  BlogCategoryModule,
  BlogPostModule,
  MenuModule,
  BannerModule,
  PopupModule,
  MediaFileModule,
  SupportTicketModule,
  TicketReplyModule,
  ContactMessageModule,
  ComplaintModule,
  KnowledgeBaseArticleModule,
  NotificationModule,
  NotificationTemplateModule,
  ApiKeyModule,
  WebhookModule,
  WebhookLogModule,
  IntegrationConnectionModule,
  OtpRequestModule,
  AiGenerationLogModule,
  SavedReportModule,
];
