import Image from "next/image";
import Link from "next/link";
import { Heart, Search, ShoppingBag, UserRound } from "lucide-react";

export default function AbraaqThemePreviewPage() {
  return <div dir="rtl" className="min-h-screen bg-[#F7F2E9] text-[#1D1915]">
    <div className="bg-[#17130F] px-4 py-2 text-center text-xs text-[#D7C19A]">شحن مجاني للطلبات فوق 500 ر.س</div>
    <header className="flex items-center justify-between border-b border-[#CBBDA8]/40 px-5 py-5 lg:px-12"><div className="flex items-center gap-4"><Search className="size-5" /><Heart className="size-5" /><UserRound className="size-5" /><ShoppingBag className="size-5" /></div><nav className="hidden items-center gap-7 text-sm lg:flex"><Link href="/">الرئيسية</Link><Link href="/shop">العطور</Link><Link href="/shop">المجموعات</Link><Link href="/about">قصتنا</Link><Link href="/contact">تواصل معنا</Link></nav><div className="text-2xl font-semibold tracking-[.18em]">إبــراق</div></header>
    <main><section className="relative min-h-[650px] overflow-hidden"><Image src="/themes/abraaq/hero.png" alt="عطر إبراق الفاخر" fill priority className="object-cover" /><div className="absolute inset-0 bg-gradient-to-l from-transparent via-transparent to-[#17130F]/65" /><div className="absolute inset-y-0 left-0 flex w-full items-center px-6 text-left sm:w-1/2 sm:px-12" dir="rtl"><div className="mr-auto max-w-xl text-right text-white"><p className="text-xs font-semibold tracking-[.25em] text-[#D7C19A]">مجموعة إبراق الجديدة</p><h1 className="mt-4 text-4xl font-semibold leading-tight sm:text-6xl">عطرٌ يترك أثرًا لا يُنسى</h1><p className="mt-5 max-w-lg leading-8 text-white/75">توليفات عطرية فاخرة مستوحاة من دفء الشرق وأناقة الحاضر.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/shop" className="bg-[#B99558] px-7 py-3 text-sm font-semibold text-[#17130F]">اكتشف المجموعة</Link><Link href="/shop" className="border border-white/50 px-7 py-3 text-sm font-semibold">تسوق الأكثر مبيعًا</Link></div></div></div></section><section className="mx-auto max-w-7xl px-5 py-20"><div className="text-center"><p className="text-xs tracking-[.25em] text-[#B99558]">مختارات إبراق</p><h2 className="mt-3 text-4xl font-semibold">عطور تحكي قصتك</h2></div><div className="mt-12 grid gap-6 md:grid-cols-3">{["عود نوار", "أمبر فيل", "مسك إكلات"].map((name, index) => <article key={name} className="bg-white p-3"><div className="relative aspect-square overflow-hidden bg-[#E9DFCF]"><Image src="/themes/abraaq/collection.png" alt={name} fill className="object-cover" style={{ objectPosition: `${index * 45}% center` }} /></div><div className="p-4 text-center"><h3 className="text-xl font-semibold">{name}</h3><p className="mt-2 text-sm text-[#74695E]">عطر شرقي فاخر · 75 مل</p><p className="mt-3 font-semibold text-[#B99558]">480 ر.س</p></div></article>)}</div></section></main>
    <footer className="bg-[#17130F] px-6 py-12 text-center text-sm text-[#CBBDA8]">إبراق · دار عطور عربية معاصرة</footer>
  </div>;
}
