"use client";
import * as React from "react";
import { Copy, FileKey2, MoreHorizontal, RefreshCw, Search, ShieldBan, ShieldCheck, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import type { DigitalLicenseKey, DigitalProductRow } from "./types";

export function LicenseKeysManager({products}:{products:DigitalProductRow[]}){
 const [query,setQuery]=React.useState("");const [keys,setKeys]=React.useState<DigitalLicenseKey[]>(products.flatMap((product)=>(product.digitalConfig?.licenseKeys??[]).map((key)=>({...key,product:key.product||product.name}))));
 const filtered=keys.filter((key)=>!query||[key.key,key.customer,key.product,key.version,key.domains].some((value)=>value.toLowerCase().includes(query.toLowerCase())));
 function update(id:string,status:string){setKeys((current)=>current.map((key)=>key.id===id?{...key,status,activationCount:status==="reset"?0:key.activationCount}:key));toast.success(`License ${status}`);}
 return <div className="space-y-4"><div><h2 className="text-lg font-bold">License Keys</h2><p className="text-sm text-muted-foreground">Monitor and control generated product licenses, activations, devices, and domains.</p></div><Card className="overflow-hidden"><div className="border-b p-4"><div className="relative max-w-sm"><Search className="absolute start-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input className="ps-9" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search key, customer, product…" /></div></div>{filtered.length===0?<div className="flex flex-col items-center gap-2 py-16 text-center"><FileKey2 className="size-10 text-muted-foreground/50" /><p className="font-semibold">No license keys yet</p><p className="max-w-sm text-sm text-muted-foreground">Keys generated after a licensed digital purchase will appear here.</p></div>:<Table><TableHeader><TableRow><TableHead>License key</TableHead><TableHead>Customer</TableHead><TableHead>Product</TableHead><TableHead>Version</TableHead><TableHead>Status</TableHead><TableHead>Activations</TableHead><TableHead>Expiration</TableHead><TableHead>Devices</TableHead><TableHead>Domains</TableHead><TableHead /></TableRow></TableHeader><TableBody>{filtered.map((key)=><TableRow key={key.id}><TableCell className="font-mono text-xs">{key.key}</TableCell><TableCell>{key.customer}</TableCell><TableCell>{key.product}</TableCell><TableCell>{key.version}</TableCell><TableCell><Badge variant={key.status==="Active"?"success":key.status==="Suspended"?"warning":"destructive"}>{key.status}</Badge></TableCell><TableCell>{key.activationCount}</TableCell><TableCell>{key.expiration||"Never"}</TableCell><TableCell>{key.devices||"—"}</TableCell><TableCell>{key.domains||"—"}</TableCell><TableCell><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon-sm"><MoreHorizontal className="size-4" /></Button></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuItem onClick={()=>update(key.id,"Active")}><ShieldCheck />Activate</DropdownMenuItem><DropdownMenuItem onClick={()=>update(key.id,"Suspended")}><ShieldBan />Suspend</DropdownMenuItem><DropdownMenuItem onClick={()=>update(key.id,"reset")}><RefreshCw />Reset activations</DropdownMenuItem><DropdownMenuItem onClick={()=>{navigator.clipboard.writeText(key.key);toast.success("License key copied");}}><Copy />Copy key</DropdownMenuItem><DropdownMenuItem variant="destructive" onClick={()=>{setKeys((current)=>current.filter((item)=>item.id!==key.id));toast.success("License revoked");}}><Trash2 />Revoke</DropdownMenuItem></DropdownMenuContent></DropdownMenu></TableCell></TableRow>)}</TableBody></Table>}</Card></div>;
}
