"use client";

import * as React from "react";
import { ChevronDown, Crop, ExternalLink, Globe2, ImagePlus, Link2, Loader2, Palette, Plus, Search, Sparkles, Trash2, UploadCloud } from "lucide-react";
import { toast } from "sonner";
import { api, ApiError } from "@/lib/api/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { cn } from "@/lib/utils";

export interface BrandItem { id:string;name:string;slug:string;description?:string|null;logo?:string|null;banner?:string|null;website?:string|null;status:string;isFeatured?:boolean;metaTitle?:string|null;metaDescription?:string|null }
interface Category { id:string;name:string }
interface ExtendedBrand { icon:string;parentBrand:string;country:string;categories:string[];tags:string;sortOrder:string;storefront:boolean;navigation:boolean;directory:boolean;supportEmail:string;facebook:string;instagram:string;linkedin:string;twitter:string;youtube:string;openGraphImage:string;canonicalUrl:string;color:string }
interface BrandForm extends ExtendedBrand { name:string;slug:string;description:string;logo:string;banner:string;website:string;status:string;featured:boolean;metaTitle:string;metaDescription:string }
const extraDefaults:ExtendedBrand={icon:"",parentBrand:"",country:"",categories:[],tags:"",sortOrder:"0",storefront:true,navigation:true,directory:true,supportEmail:"",facebook:"",instagram:"",linkedin:"",twitter:"",youtube:"",openGraphImage:"",canonicalUrl:"",color:"#4f46e5"};
const emptyForm:BrandForm={name:"",slug:"",description:"",logo:"",banner:"",website:"",status:"active",featured:false,metaTitle:"",metaDescription:"",...extraDefaults};
const slugify=(value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
const extraKey=(id:string)=>`vantage-brand-admin:${id}`;
function readExtra(id?:string):ExtendedBrand{if(!id||typeof window==="undefined")return extraDefaults;try{return{...extraDefaults,...JSON.parse(localStorage.getItem(extraKey(id))||"{}")}}catch{return extraDefaults}}

export function BrandDialog({open,onOpenChange,editing,brands,onSaved}:{open:boolean;onOpenChange:(open:boolean)=>void;editing:BrandItem|null;brands:BrandItem[];onSaved:(brand:BrandItem,editing:boolean)=>void}){
 const[categories,setCategories]=React.useState<Category[]>([]),[form,setForm]=React.useState<BrandForm>(emptyForm),[initial,setInitial]=React.useState(""),[slugTouched,setSlugTouched]=React.useState(false),[saving,setSaving]=React.useState(false),[errors,setErrors]=React.useState<Record<string,string>>({}),[seoOpen,setSeoOpen]=React.useState(false),[socialOpen,setSocialOpen]=React.useState(false),[categorySearch,setCategorySearch]=React.useState(""),[crop,setCrop]=React.useState<"center"|"top"|"bottom">("center");const nameRef=React.useRef<HTMLInputElement>(null);
 React.useEffect(()=>{if(!open)return;const task=window.setTimeout(()=>{const extra=readExtra(editing?.id);const next:BrandForm=editing?{...emptyForm,...extra,name:editing.name,slug:editing.slug,description:editing.description||"",logo:editing.logo||"",banner:editing.banner||"",website:editing.website||"",status:editing.status,featured:Boolean(editing.isFeatured),metaTitle:editing.metaTitle||"",metaDescription:editing.metaDescription||""}:emptyForm;setForm(next);setInitial(JSON.stringify(next));setSlugTouched(Boolean(editing));setErrors({});setSeoOpen(false);setSocialOpen(false);nameRef.current?.focus()},0);return()=>window.clearTimeout(task)},[open,editing]);
 React.useEffect(()=>{if(!open)return;api.get<{data:Category[]}>('/commerce/categories?limit=100').then(r=>setCategories(r.data)).catch(()=>setCategories([]));},[open]);
 const dirty=initial!==""&&JSON.stringify(form)!==initial;const set=<K extends keyof BrandForm>(key:K,value:BrandForm[K])=>{setForm(current=>({...current,[key]:value}));setErrors(current=>({...current,[key]:""}))};
 function requestClose(){if(dirty&&!window.confirm("Discard your unsaved brand changes?"))return;onOpenChange(false)}
 function validate(){const next:Record<string,string>={};const name=form.name.trim(),slug=form.slug.trim();if(!name)next.name="Brand name is required.";else if(name.length>100)next.name="Use 100 characters or fewer.";else if(brands.some(b=>b.id!==editing?.id&&b.name.trim().toLowerCase()===name.toLowerCase()))next.name="A brand with this name already exists.";if(!slug)next.slug="Slug is required.";else if(slug!==slug.toLowerCase()||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))next.slug="Use lowercase letters, numbers, and single hyphens.";else if(brands.some(b=>b.id!==editing?.id&&b.slug===slug))next.slug="This slug is already in use.";if(form.website){try{new URL(form.website)}catch{next.website="Enter a complete URL, such as https://brand.com."}}if(form.supportEmail&&!/^\S+@\S+\.\S+$/.test(form.supportEmail))next.supportEmail="Enter a valid support email.";setErrors(next);return Object.keys(next).length===0}
 async function save(mode:"normal"|"draft"|"another"="normal"){if(!validate()){toast.error("Please fix the highlighted fields");return}setSaving(true);try{const payload={name:form.name.trim(),slug:form.slug.trim(),description:form.description||undefined,logo:form.logo||undefined,banner:form.banner||undefined,website:form.website||undefined,isFeatured:form.featured,status:mode==="draft"?"draft":form.status,metaTitle:form.metaTitle||undefined,metaDescription:form.metaDescription||undefined};const saved=editing?await api.patch<BrandItem>(`/commerce/brands/${editing.id}`,payload):await api.post<BrandItem>('/commerce/brands',payload);const extended:ExtendedBrand={icon:form.icon,parentBrand:form.parentBrand,country:form.country,categories:form.categories,tags:form.tags,sortOrder:form.sortOrder,storefront:form.storefront,navigation:form.navigation,directory:form.directory,supportEmail:form.supportEmail,facebook:form.facebook,instagram:form.instagram,linkedin:form.linkedin,twitter:form.twitter,youtube:form.youtube,openGraphImage:form.openGraphImage,canonicalUrl:form.canonicalUrl,color:form.color};localStorage.setItem(extraKey(saved.id),JSON.stringify(extended));onSaved({...saved,status:mode==="draft"?"draft":saved.status},Boolean(editing));toast.success(`Brand ${editing?"updated":"created"}`);if(mode==="another"){setForm(emptyForm);setInitial(JSON.stringify(emptyForm));setSlugTouched(false);window.setTimeout(()=>nameRef.current?.focus(),50)}else onOpenChange(false)}catch(error){toast.error(error instanceof ApiError?error.message:"Could not save brand")}finally{setSaving(false)}}
 React.useEffect(()=>{if(!open)return;const handler=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key==="Enter"){event.preventDefault();void save()}};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler)});
 function upload(key:"logo"|"banner"|"icon"|"openGraphImage",file?:File){if(!file)return;const supported=["image/jpeg","image/png","image/svg+xml","image/webp"];if(!supported.includes(file.type)){setErrors(e=>({...e,[key]:"Use JPG, PNG, SVG, or WebP."}));return}if(file.size>5*1024*1024){setErrors(e=>({...e,[key]:"Image must be 5 MB or smaller."}));return}const reader=new FileReader();reader.onload=()=>set(key,String(reader.result));reader.readAsDataURL(file)}
 const filteredCategories=categories.filter(c=>c.name.toLowerCase().includes(categorySearch.toLowerCase()));
 return <Dialog open={open} onOpenChange={next=>next?onOpenChange(true):requestClose()}><DialogContent className="flex max-h-[92vh] w-[calc(100vw-1rem)] max-w-5xl flex-col gap-0 overflow-hidden p-0" onInteractOutside={event=>event.preventDefault()} onEscapeKeyDown={event=>{event.preventDefault();requestClose()}}><DialogHeader className="border-b px-5 py-4 pe-14 sm:px-6"><div className="flex items-start gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><Sparkles className="size-4.5"/></span><div><DialogTitle>{editing?"Edit Brand":"Add Brand"}</DialogTitle><DialogDescription className="mt-1">Build a storefront-ready brand profile with identity, merchandising, and search settings.</DialogDescription></div></div></DialogHeader>
 <div className="min-h-0 flex-1 overflow-y-auto"><div className="grid gap-6 p-5 sm:p-6 lg:grid-cols-[minmax(0,1fr)_270px]"><div className="space-y-6">
 <Section title="Basic Information" description="Core brand identity and customer-facing details."><div className="grid gap-4 sm:grid-cols-2"><Field label="Brand Name" required error={errors.name} counter={`${form.name.length}/100`}><Input ref={nameRef} value={form.name} maxLength={100} aria-invalid={Boolean(errors.name)} onChange={e=>{set("name",e.target.value);if(!slugTouched)set("slug",slugify(e.target.value))}} placeholder="e.g. Northstar Supply"/></Field><Field label="Slug" required error={errors.slug} hint="Lowercase URL identifier"><div className="relative"><Link2 className="absolute start-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="ps-9" value={form.slug} aria-invalid={Boolean(errors.slug)} onChange={e=>{setSlugTouched(true);set("slug",e.target.value)}} placeholder="northstar-supply"/></div></Field><Field label="Official Website" error={errors.website}><div className="relative"><Globe2 className="absolute start-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="ps-9" value={form.website} aria-invalid={Boolean(errors.website)} onChange={e=>set("website",e.target.value)} placeholder="https://brand.com"/></div></Field><Field label="Brand color"><div className="flex gap-2"><Input type="color" className="w-14 p-1" value={form.color} onChange={e=>set("color",e.target.value)}/><Input value={form.color} onChange={e=>set("color",e.target.value)}/></div></Field><Field className="sm:col-span-2" label="Description" counter={`${form.description.length}/500`}><Textarea rows={4} maxLength={500} value={form.description} onChange={e=>set("description",e.target.value)} placeholder="Tell customers what makes this brand distinctive…"/></Field></div></Section>
 <Section title="Brand Identity" description="Upload optimized assets for cards, navigation, and campaigns."><div className="grid gap-4 sm:grid-cols-3"><ImageField label="Brand Logo" value={form.logo} required error={errors.logo} crop={crop} onCrop={()=>setCrop(crop==="center"?"top":crop==="top"?"bottom":"center")} onUpload={file=>upload("logo",file)} onRemove={()=>set("logo","")}/><ImageField label="Cover Image" value={form.banner} crop={crop} onCrop={()=>setCrop(crop==="center"?"top":crop==="top"?"bottom":"center")} onUpload={file=>upload("banner",file)} onRemove={()=>set("banner","")}/><ImageField label="Brand Icon" value={form.icon} crop={crop} onCrop={()=>setCrop(crop==="center"?"top":crop==="top"?"bottom":"center")} onUpload={file=>upload("icon",file)} onRemove={()=>set("icon","")}/></div><p className="mt-3 text-[11px] text-muted-foreground">JPG, PNG, SVG, or WebP · Maximum 5 MB. Drag an image onto any upload area.</p></Section>
 <Section title="Organization" description="Group the brand for governance and catalog discovery."><div className="grid gap-4 sm:grid-cols-2"><Field label="Parent Brand"><Select value={form.parentBrand||"none"} onValueChange={v=>set("parentBrand",v==="none"?"":v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">No parent brand</SelectItem>{brands.filter(b=>b.id!==editing?.id).map(b=><SelectItem key={b.id} value={b.id}>{b.name}</SelectItem>)}</SelectContent></Select></Field><Field label="Country of Origin"><Input value={form.country} onChange={e=>set("country",e.target.value)} placeholder="United States"/></Field><Field label="Tags"><Input value={form.tags} onChange={e=>set("tags",e.target.value)} placeholder="premium, sustainable, sportswear"/></Field><Field label="Sort Order"><Input type="number" min="0" value={form.sortOrder} onChange={e=>set("sortOrder",e.target.value)}/></Field><Field className="sm:col-span-2" label="Brand Categories"><div className="rounded-xl border p-3"><div className="relative mb-2"><Search className="absolute start-3 top-1/2 size-3.5 -translate-y-1/2 text-muted-foreground"/><Input className="h-8 ps-8" value={categorySearch} onChange={e=>setCategorySearch(e.target.value)} placeholder="Find categories…"/></div><div className="grid max-h-32 gap-1 overflow-y-auto sm:grid-cols-2">{filteredCategories.map(c=><label key={c.id} className="flex cursor-pointer items-center gap-2 rounded-lg px-2 py-1.5 text-sm hover:bg-secondary"><Checkbox checked={form.categories.includes(c.id)} onCheckedChange={checked=>set("categories",checked?[...form.categories,c.id]:form.categories.filter(id=>id!==c.id))}/>{c.name}</label>)}</div></div></Field></div></Section>
 <Section title="Visibility" description="Control publication and storefront placement."><div className="grid gap-3 sm:grid-cols-2"><Field label="Status"><Select value={form.status} onValueChange={v=>set("status",v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["active","draft","inactive","archived"].map(s=><SelectItem key={s} value={s}>{s[0].toUpperCase()+s.slice(1)}</SelectItem>)}</SelectContent></Select></Field><div/><Toggle label="Featured Brand" description="Promote in curated placements" checked={form.featured} onChange={v=>set("featured",v)}/><Toggle label="Show on Storefront" description="Publish customer-facing pages" checked={form.storefront} onChange={v=>set("storefront",v)}/><Toggle label="Show in Navigation" description="Allow menu placement" checked={form.navigation} onChange={v=>set("navigation",v)}/><Toggle label="Show in Brand Directory" description="Include in brand discovery" checked={form.directory} onChange={v=>set("directory",v)}/></div></Section>
 <Expandable title="SEO Settings" description="Search metadata, canonical URL, and social previews." open={seoOpen} onOpenChange={setSeoOpen}><div className="grid gap-4 sm:grid-cols-2"><Field className="sm:col-span-2" label="SEO Title" counter={`${form.metaTitle.length}/60`}><Input maxLength={60} value={form.metaTitle} onChange={e=>set("metaTitle",e.target.value)}/></Field><Field className="sm:col-span-2" label="Meta Description" counter={`${form.metaDescription.length}/160`}><Textarea maxLength={160} rows={3} value={form.metaDescription} onChange={e=>set("metaDescription",e.target.value)}/></Field><Field label="Open Graph Image"><Input value={form.openGraphImage} onChange={e=>set("openGraphImage",e.target.value)} placeholder="https://…"/></Field><Field label="Canonical URL"><Input value={form.canonicalUrl} onChange={e=>set("canonicalUrl",e.target.value)} placeholder="https://store.com/brands/…"/></Field></div></Expandable>
 <Expandable title="Contact & Social" description="Official support and verified social profiles." open={socialOpen} onOpenChange={setSocialOpen}><div className="grid gap-4 sm:grid-cols-2"><Field label="Official Website"><Input value={form.website} onChange={e=>set("website",e.target.value)}/></Field><Field label="Support Email" error={errors.supportEmail}><Input type="email" value={form.supportEmail} onChange={e=>set("supportEmail",e.target.value)}/></Field>{(["facebook","instagram","linkedin","twitter","youtube"] as const).map(key=><Field key={key} label={key==="twitter"?"X (Twitter)":key[0].toUpperCase()+key.slice(1)}><Input value={form[key]} onChange={e=>set(key,e.target.value)} placeholder="https://…"/></Field>)}</div></Expandable>
 </div><aside className="space-y-4 lg:sticky lg:top-0 lg:self-start"><div className="overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="h-24" style={{background:`linear-gradient(135deg, ${form.color}, color-mix(in srgb, ${form.color} 35%, transparent))`}}>{form.banner&&<img src={form.banner} alt="" className="size-full object-cover"/>}</div><div className="p-4 pt-0"><div className="-mt-7 mb-3 flex size-14 items-center justify-center overflow-hidden rounded-2xl border-4 border-card bg-secondary shadow-sm">{form.logo?<img src={form.logo} alt="" className="size-full object-cover"/>:<Palette className="size-5 text-muted-foreground"/>}</div><div className="flex items-center gap-2"><h3 className="truncate font-semibold">{form.name||"Brand preview"}</h3>{form.featured&&<Badge variant="warning">Featured</Badge>}</div><p className="mt-1 line-clamp-3 text-xs text-muted-foreground">{form.description||"Your brand description will appear here."}</p>{form.website&&<p className="mt-3 flex items-center gap-1 truncate text-xs text-primary"><ExternalLink className="size-3"/>{form.website}</p>}</div></div><div className="rounded-2xl border p-4"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Recently used</p><div className="mt-3 flex flex-wrap gap-2">{brands.slice(0,5).map(b=><Badge key={b.id} variant="outline">{b.name}</Badge>)}</div></div><div className="rounded-2xl border bg-primary/[.03] p-4 text-xs text-muted-foreground"><p className="font-semibold text-foreground">Keyboard shortcut</p><p className="mt-1">Press <kbd className="rounded border bg-background px-1.5 py-0.5">⌘/Ctrl + Enter</kbd> to save.</p></div></aside></div></div>
 <footer className="flex shrink-0 flex-col-reverse gap-2 border-t bg-background/95 px-5 py-4 backdrop-blur sm:flex-row sm:items-center sm:justify-between sm:px-6"><Button variant="ghost" onClick={requestClose} disabled={saving}>Cancel</Button><div className="flex flex-col gap-2 sm:flex-row"><Button variant="outline" onClick={()=>save("draft")} disabled={saving}>Save as Draft</Button><Button onClick={()=>save()} disabled={saving}>{saving?<Loader2 className="size-4 animate-spin"/>:null}Save Brand</Button><Button variant="secondary" onClick={()=>save("another")} disabled={saving}><Plus className="size-4"/>Save & Add Another</Button></div></footer></DialogContent></Dialog>
}

function Section({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <section className="rounded-2xl border bg-card p-4 shadow-sm sm:p-5"><div className="mb-4"><h3 className="font-semibold">{title}</h3><p className="mt-0.5 text-xs text-muted-foreground">{description}</p></div>{children}</section>}
function Field({label,required,error,hint,counter,className,children}:{label:string;required?:boolean;error?:string;hint?:string;counter?:string;className?:string;children:React.ReactNode}){return <div className={cn("space-y-1.5",className)}><div className="flex items-center justify-between gap-2"><Label>{label}{required&&<span className="text-destructive"> *</span>}</Label>{counter&&<span className="text-[10px] text-muted-foreground">{counter}</span>}</div>{children}{error?<p className="text-xs text-destructive">{error}</p>:hint?<p className="text-[11px] text-muted-foreground">{hint}</p>:null}</div>}
function Toggle({label,description,checked,onChange}:{label:string;description:string;checked:boolean;onChange:(v:boolean)=>void}){return <div className="flex items-center justify-between gap-3 rounded-xl border p-3"><div><Label>{label}</Label><p className="text-[11px] text-muted-foreground">{description}</p></div><Switch checked={checked} onCheckedChange={onChange}/></div>}
function Expandable({title,description,open,onOpenChange,children}:{title:string;description:string;open:boolean;onOpenChange:(v:boolean)=>void;children:React.ReactNode}){return <Collapsible open={open} onOpenChange={onOpenChange} className="rounded-2xl border bg-card shadow-sm"><CollapsibleTrigger className="flex w-full items-center justify-between gap-4 p-4 text-start sm:p-5"><div><h3 className="font-semibold">{title}</h3><p className="mt-0.5 text-xs text-muted-foreground">{description}</p></div><ChevronDown className={cn("size-4 transition-transform",open&&"rotate-180")}/></CollapsibleTrigger><CollapsibleContent><div className="border-t p-4 sm:p-5">{children}</div></CollapsibleContent></Collapsible>}
function ImageField({label,value,required,error,crop,onUpload,onRemove,onCrop}:{label:string;value:string;required?:boolean;error?:string;crop:string;onUpload:(file?:File)=>void;onRemove:()=>void;onCrop:()=>void}){const input=React.useRef<HTMLInputElement>(null);return <div className="space-y-1.5"><Label>{label}{required&&<span className="text-destructive"> *</span>}</Label><div className={cn("group relative flex aspect-[4/3] items-center justify-center overflow-hidden rounded-xl border border-dashed bg-secondary/30 transition-colors hover:border-primary/50",error&&"border-destructive")} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();onUpload(e.dataTransfer.files[0])}}>{value?<><img src={value} alt={`${label} preview`} className="size-full object-cover" style={{objectPosition:crop}}/><div className="absolute inset-0 flex items-center justify-center gap-1 bg-black/50 opacity-0 transition-opacity group-hover:opacity-100"><Button size="icon-sm" variant="secondary" onClick={()=>input.current?.click()} aria-label={`Replace ${label}`}><UploadCloud className="size-3.5"/></Button><Button size="icon-sm" variant="secondary" onClick={onCrop} aria-label={`Crop ${label}`}><Crop className="size-3.5"/></Button><Button size="icon-sm" variant="destructive" onClick={onRemove} aria-label={`Remove ${label}`}><Trash2 className="size-3.5"/></Button></div></>:<button type="button" className="flex size-full flex-col items-center justify-center p-3 text-center" onClick={()=>input.current?.click()}><span className="mb-2 flex size-9 items-center justify-center rounded-xl bg-background shadow-sm"><ImagePlus className="size-4 text-primary"/></span><span className="text-xs font-medium">Drop or browse</span><span className="mt-0.5 text-[10px] text-muted-foreground">JPG, PNG, SVG, WebP</span></button>}<input ref={input} type="file" className="hidden" accept="image/jpeg,image/png,image/svg+xml,image/webp" onChange={e=>onUpload(e.target.files?.[0])}/></div>{error&&<p className="text-xs text-destructive">{error}</p>}</div>}
