"use client";

import * as React from "react";
import { BarChart3, ChevronDown, Crop, FolderTree, ImagePlus, Link2, Loader2, Package, Palette, Plus, ShoppingCart, Trash2, UploadCloud } from "lucide-react";
import { toast } from "sonner";
import { api, ApiError } from "@/lib/api/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { cn, formatCurrency, formatNumber } from "@/lib/utils";

export interface CategoryItem{id:string;name:string;slug:string;description?:string|null;image?:string|null;icon?:string|null;banner?:string|null;parentId?:string|null;displayOrder?:number;isFeatured?:boolean;status:string;metaTitle?:string|null;metaDescription?:string|null}
interface Extra{type:string;shortDescription:string;storefront:boolean;navigation:boolean;homepage:boolean;search:boolean;mobile:boolean;layout:string;sorting:string;perPage:string;filters:string[];audience:string;canonical:string;openGraph:string;color:string;views:number;orders:number;revenue:number;products:number}
interface Form extends Extra{name:string;slug:string;description:string;image:string;icon:string;banner:string;parentId:string;displayOrder:string;featured:boolean;status:string;metaTitle:string;metaDescription:string}
const defaults:Extra={type:"Standard",shortDescription:"",storefront:true,navigation:true,homepage:false,search:true,mobile:true,layout:"Grid",sorting:"Featured",perPage:"24",filters:["Brand","Price","Availability"],audience:"Public",canonical:"",openGraph:"",color:"#4f46e5",views:0,orders:0,revenue:0,products:0};
const blank:Form={name:"",slug:"",description:"",image:"",icon:"",banner:"",parentId:"",displayOrder:"0",featured:false,status:"active",metaTitle:"",metaDescription:"",...defaults};
const key=(id:string)=>`vantage-category-admin:${id}`;const slugify=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
function extra(id?:string){if(!id||typeof window==="undefined")return defaults;try{return{...defaults,...JSON.parse(localStorage.getItem(key(id))||"{}")}}catch{return defaults}}

export function CategoryDialog({open,onOpenChange,editing,categories,onSaved}:{open:boolean;onOpenChange:(v:boolean)=>void;editing:CategoryItem|null;categories:CategoryItem[];onSaved:(item:CategoryItem,editing:boolean)=>void}){
 const[form,setForm]=React.useState<Form>(blank),[initial,setInitial]=React.useState(""),[slugTouched,setSlugTouched]=React.useState(false),[saving,setSaving]=React.useState(false),[errors,setErrors]=React.useState<Record<string,string>>({}),[displayOpen,setDisplayOpen]=React.useState(false),[seoOpen,setSeoOpen]=React.useState(false),[filtersOpen,setFiltersOpen]=React.useState(false),[crop,setCrop]=React.useState<"center"|"top"|"bottom">("center");const nameRef=React.useRef<HTMLInputElement>(null);
 React.useEffect(()=>{if(!open)return;const task=window.setTimeout(()=>{const next:Form=editing?{...blank,...extra(editing.id),name:editing.name,slug:editing.slug,description:editing.description||"",image:editing.image||"",icon:editing.icon||"",banner:editing.banner||"",parentId:editing.parentId||"",displayOrder:String(editing.displayOrder||0),featured:Boolean(editing.isFeatured),status:editing.status,metaTitle:editing.metaTitle||"",metaDescription:editing.metaDescription||""}:blank;setForm(next);setInitial(JSON.stringify(next));setSlugTouched(Boolean(editing));setErrors({});setDisplayOpen(false);setSeoOpen(false);setFiltersOpen(false);nameRef.current?.focus()},0);return()=>window.clearTimeout(task)},[open,editing]);
 const dirty=initial!==""&&JSON.stringify(form)!==initial;const set=<K extends keyof Form>(k:K,v:Form[K])=>{setForm(f=>({...f,[k]:v}));setErrors(e=>({...e,[k]:""}))};
 function close(){if(dirty&&!window.confirm("Discard your unsaved category changes?"))return;onOpenChange(false)}
 function validate(){const e:Record<string,string>={};const name=form.name.trim(),slug=form.slug.trim();if(!name)e.name="Category name is required.";else if(name.length>100)e.name="Use 100 characters or fewer.";else if(categories.some(c=>c.id!==editing?.id&&c.name.toLowerCase()===name.toLowerCase()))e.name="A category with this name already exists.";if(!slug)e.slug="Slug is required.";else if(slug!==slug.toLowerCase()||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))e.slug="Use lowercase letters, numbers, and single hyphens.";else if(categories.some(c=>c.id!==editing?.id&&c.slug===slug))e.slug="This slug is already in use.";setErrors(e);return !Object.keys(e).length}
 async function save(mode:"normal"|"draft"|"another"="normal"){if(!validate()){toast.error("Please fix the highlighted fields");return}setSaving(true);try{const payload={name:form.name.trim(),slug:form.slug.trim(),description:form.description||form.shortDescription||undefined,image:form.image||undefined,icon:form.icon||undefined,banner:form.banner||undefined,parentId:form.parentId||undefined,displayOrder:Number(form.displayOrder),isFeatured:form.featured,status:mode==="draft"?"draft":form.status,metaTitle:form.metaTitle||undefined,metaDescription:form.metaDescription||undefined};const saved=editing?await api.patch<CategoryItem>(`/commerce/categories/${editing.id}`,payload):await api.post<CategoryItem>('/commerce/categories',payload);const admin:Extra={type:form.type,shortDescription:form.shortDescription,storefront:form.storefront,navigation:form.navigation,homepage:form.homepage,search:form.search,mobile:form.mobile,layout:form.layout,sorting:form.sorting,perPage:form.perPage,filters:form.filters,audience:form.audience,canonical:form.canonical,openGraph:form.openGraph,color:form.color,views:form.views,orders:form.orders,revenue:form.revenue,products:form.products};localStorage.setItem(key(saved.id),JSON.stringify(admin));onSaved({...saved,status:mode==="draft"?"draft":saved.status},Boolean(editing));toast.success(`Category ${editing?"updated":"created"}`);if(mode==="another"){setForm(blank);setInitial(JSON.stringify(blank));setSlugTouched(false);window.setTimeout(()=>nameRef.current?.focus(),50)}else onOpenChange(false)}catch(error){toast.error(error instanceof ApiError?error.message:"Could not save category")}finally{setSaving(false)}}
 React.useEffect(()=>{if(!open)return;const handler=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key==="Enter"){event.preventDefault();void save()}};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler)});
 function upload(field:"image"|"banner"|"icon"|"openGraph",file?:File){if(!file)return;if(!["image/jpeg","image/png","image/svg+xml","image/webp"].includes(file.type)){setErrors(e=>({...e,[field]:"Use JPG, PNG, SVG, or WebP."}));return}if(file.size>5*1024*1024){setErrors(e=>({...e,[field]:"Image must be 5 MB or smaller."}));return}const reader=new FileReader();reader.onload=()=>set(field,String(reader.result));reader.readAsDataURL(file)}
 const parent=categories.find(c=>c.id===form.parentId),hierarchy=parent?`${parent.name}  ›  ${form.name||"New category"}`:form.name||"Root category";
 return <Dialog open={open} onOpenChange={next=>next?onOpenChange(true):close()}><DialogContent className="flex max-h-[92vh] w-[calc(100vw-1rem)] max-w-5xl flex-col gap-0 overflow-hidden p-0" onInteractOutside={e=>e.preventDefault()} onEscapeKeyDown={e=>{e.preventDefault();close()}}><DialogHeader className="border-b px-5 py-4 pe-14 sm:px-6"><div className="flex gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><FolderTree className="size-4.5"/></span><div><DialogTitle>{editing?"Edit Category":"Add Category"}</DialogTitle><DialogDescription className="mt-1">Create a scalable catalog destination with hierarchy, merchandising, and storefront rules.</DialogDescription></div></div></DialogHeader>
 <div className="min-h-0 flex-1 overflow-y-auto"><div className="grid gap-6 p-5 sm:p-6 lg:grid-cols-[minmax(0,1fr)_270px]"><div className="space-y-6"><Section title="Basic Information" description="Name, classify, and position this category in the catalog."><div className="grid gap-4 sm:grid-cols-2"><Field label="Category Name" required error={errors.name} counter={`${form.name.length}/100`}><Input ref={nameRef} maxLength={100} value={form.name} onChange={e=>{set("name",e.target.value);if(!slugTouched)set("slug",slugify(e.target.value))}} placeholder="e.g. Smartphones"/></Field><Field label="Slug" required error={errors.slug} hint="Lowercase URL identifier"><div className="relative"><Link2 className="absolute start-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="ps-9" value={form.slug} onChange={e=>{setSlugTouched(true);set("slug",e.target.value)}} placeholder="smartphones"/></div></Field><Field label="Parent Category"><Select value={form.parentId||"none"} onValueChange={v=>set("parentId",v==="none"?"":v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Root category</SelectItem>{categories.filter(c=>c.id!==editing?.id).map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></Field><Field label="Category Type"><Select value={form.type} onValueChange={v=>set("type",v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["Standard","Digital","Wholesale","Auction","Service","Blog","Custom"].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></Field><Field className="sm:col-span-2" label="Short Description" counter={`${form.shortDescription.length}/160`}><Textarea rows={2} maxLength={160} value={form.shortDescription} onChange={e=>set("shortDescription",e.target.value)}/></Field><Field className="sm:col-span-2" label="Description" counter={`${form.description.length}/800`}><Textarea rows={5} maxLength={800} value={form.description} onChange={e=>set("description",e.target.value)}/></Field></div></Section>
 <Section title="Category Media" description="Upload optimized imagery for navigation, landing pages, and mobile."><div className="grid gap-4 sm:grid-cols-3"><ImageField label="Category Image" value={form.image} crop={crop} error={errors.image} onUpload={f=>upload("image",f)} onRemove={()=>set("image","")} onCrop={()=>setCrop(crop==="center"?"top":crop==="top"?"bottom":"center")}/><ImageField label="Category Banner" value={form.banner} crop={crop} error={errors.banner} onUpload={f=>upload("banner",f)} onRemove={()=>set("banner","")} onCrop={()=>setCrop(crop==="center"?"top":crop==="top"?"bottom":"center")}/><ImageField label="Category Icon" value={form.icon} crop={crop} error={errors.icon} onUpload={f=>upload("icon",f)} onRemove={()=>set("icon","")} onCrop={()=>setCrop(crop==="center"?"top":crop==="top"?"bottom":"center")}/></div><p className="mt-3 text-[11px] text-muted-foreground">JPG, PNG, SVG, or WebP · Maximum 5 MB · Drag and drop supported.</p></Section>
 <Section title="Hierarchy & Visibility" description="Control ordering, publication, and discovery across channels."><div className="mb-4 rounded-xl border bg-secondary/30 p-3"><p className="text-[11px] font-medium text-muted-foreground">CATEGORY PATH</p><p className="mt-1 text-sm font-semibold">{hierarchy}</p></div><div className="grid gap-3 sm:grid-cols-2"><Field label="Sort Order"><Input type="number" min="0" value={form.displayOrder} onChange={e=>set("displayOrder",e.target.value)}/></Field><Field label="Status"><Select value={form.status} onValueChange={v=>set("status",v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["active","draft","hidden","archived"].map(v=><SelectItem key={v} value={v}>{v[0].toUpperCase()+v.slice(1)}</SelectItem>)}</SelectContent></Select></Field><Toggle label="Featured Category" hint="Promote in curated placements" value={form.featured} onChange={v=>set("featured",v)}/><Toggle label="Show on Storefront" hint="Publish the category page" value={form.storefront} onChange={v=>set("storefront",v)}/><Toggle label="Show in Navigation" hint="Allow menu placement" value={form.navigation} onChange={v=>set("navigation",v)}/><Toggle label="Homepage Sections" hint="Available to page builder" value={form.homepage} onChange={v=>set("homepage",v)}/><Toggle label="Show in Search" hint="Include in category results" value={form.search} onChange={v=>set("search",v)}/><Toggle label="Show in Mobile App" hint="Publish to mobile channels" value={form.mobile} onChange={v=>set("mobile",v)}/></div></Section>
 <Expandable title="Display Settings" description="Layout, sorting, pagination, and customer visibility." open={displayOpen} onOpenChange={setDisplayOpen}><div className="grid gap-4 sm:grid-cols-2"><Field label="Default Layout"><Select value={form.layout} onValueChange={v=>set("layout",v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Grid">Grid</SelectItem><SelectItem value="List">List</SelectItem></SelectContent></Select></Field><Field label="Products Per Page"><Input type="number" min="1" max="100" value={form.perPage} onChange={e=>set("perPage",e.target.value)}/></Field><Field label="Default Product Sorting"><Select value={form.sorting} onValueChange={v=>set("sorting",v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["Featured","Best Selling","Newest","Price Low to High","Price High to Low","Highest Rated"].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></Field><Field label="Customer Visibility"><Select value={form.audience} onValueChange={v=>set("audience",v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["Public","Registered Customers","Customer Groups","Wholesale Customers","Members Only","Private"].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></Field></div></Expandable>
 <Expandable title="Category Filters" description="Choose filters customers can use within this category." open={filtersOpen} onOpenChange={setFiltersOpen}><div className="grid gap-2 sm:grid-cols-2 md:grid-cols-4">{["Brand","Price","Size","Colour","Material","Rating","Availability","Tags"].map(v=><label key={v} className="flex cursor-pointer items-center gap-2 rounded-xl border p-3 text-sm"><Checkbox checked={form.filters.includes(v)} onCheckedChange={checked=>set("filters",checked?[...form.filters,v]:form.filters.filter(x=>x!==v))}/>{v}</label>)}</div></Expandable>
 <Expandable title="SEO Settings" description="Search metadata, canonical URL, and social sharing preview." open={seoOpen} onOpenChange={setSeoOpen}><div className="grid gap-4 sm:grid-cols-2"><Field className="sm:col-span-2" label="SEO Title" counter={`${form.metaTitle.length}/60`}><Input maxLength={60} value={form.metaTitle} onChange={e=>set("metaTitle",e.target.value)}/></Field><Field className="sm:col-span-2" label="Meta Description" counter={`${form.metaDescription.length}/160`}><Textarea rows={3} maxLength={160} value={form.metaDescription} onChange={e=>set("metaDescription",e.target.value)}/></Field><Field label="Canonical URL"><Input value={form.canonical} onChange={e=>set("canonical",e.target.value)} placeholder="https://store.com/category/…"/></Field><Field label="Open Graph Image"><Input value={form.openGraph} onChange={e=>set("openGraph",e.target.value)} placeholder="https://…"/></Field></div></Expandable></div>
 <aside className="space-y-4 lg:sticky lg:top-0 lg:self-start"><div className="overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="h-28" style={{background:`linear-gradient(135deg,${form.color},transparent)`}}>{form.banner&&<img src={form.banner} alt="" className="size-full object-cover"/>}</div><div className="p-4"><div className="flex items-center gap-3">{form.image?<img src={form.image} alt="" className="size-12 rounded-xl object-cover"/>:<span className="flex size-12 items-center justify-center rounded-xl bg-primary/10 text-primary"><FolderTree className="size-5"/></span>}<div><h3 className="font-semibold">{form.name||"Category preview"}</h3><p className="text-xs text-muted-foreground">{form.type} · {form.layout}</p></div></div><p className="mt-3 line-clamp-3 text-xs text-muted-foreground">{form.shortDescription||"Your category introduction will appear here."}</p><div className="mt-3 flex gap-2"><Badge variant={form.status==="active"?"success":"secondary"}>{form.status}</Badge>{form.featured&&<Badge variant="warning">Featured</Badge>}</div></div></div><div className="rounded-2xl border p-4"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Branding color</p><Input type="color" className="h-8 w-10 p-1" value={form.color} onChange={e=>set("color",e.target.value)}/></div></div>{editing&&<div className="grid grid-cols-2 gap-2">{[{label:"Products",value:formatNumber(form.products),icon:Package},{label:"Views",value:formatNumber(form.views),icon:BarChart3},{label:"Orders",value:formatNumber(form.orders),icon:ShoppingCart},{label:"Revenue",value:formatCurrency(form.revenue),icon:Palette}].map(m=><div key={m.label} className="rounded-xl border p-3"><m.icon className="mb-2 size-3.5 text-primary"/><p className="text-xs text-muted-foreground">{m.label}</p><p className="font-bold">{m.value}</p></div>)}</div>}<div className="rounded-2xl border p-4"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Recent parents</p><div className="mt-3 flex flex-wrap gap-2">{categories.slice(0,5).map(c=><Badge key={c.id} variant="outline">{c.name}</Badge>)}</div></div></aside></div></div>
 <footer className="flex shrink-0 flex-col-reverse gap-2 border-t bg-background/95 px-5 py-4 backdrop-blur sm:flex-row sm:items-center sm:justify-between sm:px-6"><Button variant="ghost" onClick={close} disabled={saving}>Cancel</Button><div className="flex flex-col gap-2 sm:flex-row"><Button variant="outline" onClick={()=>save("draft")} disabled={saving}>Save as Draft</Button><Button onClick={()=>save()} disabled={saving}>{saving&&<Loader2 className="size-4 animate-spin"/>}Save Category</Button><Button variant="secondary" onClick={()=>save("another")} disabled={saving}><Plus className="size-4"/>Save & Add Another</Button></div></footer></DialogContent></Dialog>
}
function Section({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <section className="rounded-2xl border bg-card p-4 shadow-sm sm:p-5"><h3 className="font-semibold">{title}</h3><p className="mb-4 mt-0.5 text-xs text-muted-foreground">{description}</p>{children}</section>}
function Field({label,required,error,hint,counter,className,children}:{label:string;required?:boolean;error?:string;hint?:string;counter?:string;className?:string;children:React.ReactNode}){return <div className={cn("space-y-1.5",className)}><div className="flex justify-between gap-2"><Label>{label}{required&&<span className="text-destructive"> *</span>}</Label>{counter&&<span className="text-[10px] text-muted-foreground">{counter}</span>}</div>{children}{error?<p className="text-xs text-destructive">{error}</p>:hint?<p className="text-[11px] text-muted-foreground">{hint}</p>:null}</div>}
function Toggle({label,hint,value,onChange}:{label:string;hint:string;value:boolean;onChange:(v:boolean)=>void}){return <div className="flex items-center justify-between rounded-xl border p-3"><div><Label>{label}</Label><p className="text-[11px] text-muted-foreground">{hint}</p></div><Switch checked={value} onCheckedChange={onChange}/></div>}
function Expandable({title,description,open,onOpenChange,children}:{title:string;description:string;open:boolean;onOpenChange:(v:boolean)=>void;children:React.ReactNode}){return <Collapsible open={open} onOpenChange={onOpenChange} className="rounded-2xl border bg-card shadow-sm"><CollapsibleTrigger className="flex w-full items-center justify-between p-4 text-start sm:p-5"><div><h3 className="font-semibold">{title}</h3><p className="mt-0.5 text-xs text-muted-foreground">{description}</p></div><ChevronDown className={cn("size-4 transition-transform",open&&"rotate-180")}/></CollapsibleTrigger><CollapsibleContent><div className="border-t p-4 sm:p-5">{children}</div></CollapsibleContent></Collapsible>}
function ImageField({label,value,error,crop,onUpload,onRemove,onCrop}:{label:string;value:string;error?:string;crop:string;onUpload:(f?:File)=>void;onRemove:()=>void;onCrop:()=>void}){const ref=React.useRef<HTMLInputElement>(null);return <div className="space-y-1.5"><Label>{label}</Label><div className={cn("group relative flex aspect-[4/3] items-center justify-center overflow-hidden rounded-xl border border-dashed bg-secondary/30 hover:border-primary/50",error&&"border-destructive")} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();onUpload(e.dataTransfer.files[0])}}>{value?<><img src={value} alt={`${label} preview`} className="size-full object-cover" style={{objectPosition:crop}}/><div className="absolute inset-0 flex items-center justify-center gap-1 bg-black/50 opacity-0 group-hover:opacity-100"><Button size="icon-sm" variant="secondary" onClick={()=>ref.current?.click()}><UploadCloud className="size-3.5"/></Button><Button size="icon-sm" variant="secondary" onClick={onCrop}><Crop className="size-3.5"/></Button><Button size="icon-sm" variant="destructive" onClick={onRemove}><Trash2 className="size-3.5"/></Button></div></>:<button type="button" className="flex size-full flex-col items-center justify-center" onClick={()=>ref.current?.click()}><ImagePlus className="mb-2 size-5 text-primary"/><span className="text-xs font-medium">Drop or browse</span></button>}<input ref={ref} type="file" className="hidden" accept="image/jpeg,image/png,image/svg+xml,image/webp" onChange={e=>onUpload(e.target.files?.[0])}/></div>{error&&<p className="text-xs text-destructive">{error}</p>}</div>}
